# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc68c50bda8c99116bd9261b62b830bfa770d47a1ba2d66e5363fe47e5bcdb0a70ba0dacc7daaa0d4cfa40df5f83114623e3dae4e2bf38a8484dde63a46ba85c

test:
  secret_key_base: 37385211eb5ad92374860ac12fecc8e0e857087cd3992bdd0d0b15ea10ac0a52a8dbfa792361865fb981b85a4dbab4a0ceac2efdc852b3c5ba4972bcec1f1356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
